"""Final database models

Revision ID: c6a5cdef6222
Revises: 
Create Date: 2025-09-12 18:49:41.222777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a5cdef6222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('baseGroups', sa.JSON(), nullable=True),
    sa.Column('monthlyPriorities', sa.JSON(), nullable=True),
    sa.Column('assignments', sa.JSON(), nullable=True),
    sa.Column('shifts_per_day', sa.Integer(), nullable=False),
    sa.Column('shift_overrides', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('engineer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('maxShifts', sa.Integer(), nullable=False),
    sa.Column('consecutive_pref', sa.String(length=10), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engineer')
    op.drop_table('team')
    op.drop_table('setting')
    op.drop_table('holiday')
    # ### end Alembic commands ###
